apiVersion: v1
kind: ServiceAccount
metadata:
  name: brain-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: brain-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create","delete","get","list"]
- apiGroups: [""]
  resources: ["pods","pods/log"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: brain-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: brain-role
subjects:
- kind: ServiceAccount
  name: brain-sa
  namespace: default